In [1]:
import torch

Auto Gradient

In [3]:
x = torch.ones(2,2,requires_grad = True)

y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [5]:
z = y*y*3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [7]:
a = torch.randn(2,2)
a = ((a*3)/(a-1))
print(a)

tensor([[-9.0444,  6.4030],
        [14.3388, -2.8447]])


In [8]:
out.backward()

In [9]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [ ]:
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 3x3 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

In [4]:
import torch

In [9]:
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    
    def __init__(self):
        super(Net,self).__init__()
        self.conv1 = nn.Conv2d(1,6,3)
        self.conv2 = nn.Conv2d(6,16,3)
        self.fc1 = nn.Linear(16*6*6,120)
        self.fc2 = nn.Linear(120,84)
        self.fc3 = nn.Linear(84,10)
        
    def forward(self,x):
        x = F.max_pool2d(F.relu(self.conv1(x)),(2,2))
        
        x = F.max_pool2d(F.relu(self.conv2(x)),2)
        x = x.view(-1,self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def num_flat_features(self,x):
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s
        return num_features
    
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [10]:
input = torch.rand(1,1,32,32)
out = net(input)
print(out)

tensor([[ 0.0049, -0.0804, -0.0551,  0.0185, -0.0682,  0.0028,  0.1127,  0.0694,
         -0.0833,  0.0890]], grad_fn=<AddmmBackward>)


In [12]:
net.zero_grad()
out.backward(torch.randn(1,10))

In [15]:
target = torch.randn(10)
print(target)
target = target.view(1,-1)
print(target)

tensor([ 0.6583,  0.8319,  2.6834, -0.1241, -1.3642, -1.1421, -0.7096,  0.5469,
         0.8340, -0.1071])
tensor([[ 0.6583,  0.8319,  2.6834, -0.1241, -1.3642, -1.1421, -0.7096,  0.5469,
          0.8340, -0.1071]])


In [17]:
import torch
import torchvision
import torchvision.transforms as transforms

In [28]:
a = torch.randn(2,3)
print(a)

tensor([[-0.7138, -0.0025, -0.2404],
        [ 0.0080,  0.0023, -0.6110]])


In [30]:
b = a.view(3,2)
print(b)
b = a.view(-1,2)
print(b)

tensor([[-0.7138, -0.0025],
        [-0.2404,  0.0080],
        [ 0.0023, -0.6110]])
tensor([[-0.7138, -0.0025],
        [-0.2404,  0.0080],
        [ 0.0023, -0.6110]])


In [31]:
class Net(nn.Module):
    
    def __init__(self):
        super(Net,self).__init__()
        self.conv1 = nn.Conv2d(3,6,5)
        self.pool = nn.MaxPool2d(2,2)
        self.conv2 = nn.Conv2d(6,16,5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        
    def forward(self,x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1,16*5*5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
net = Net()

In [32]:
import torch.optim as optim

criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr = 0.001, momentum=0.9)

In [ ]:
for epoch in range(2):
    
    running_loss = 0.0
    for i , data in enumerate(trainloader, 0):
        inputs, labels = data
        
        optimizer.zero_grad()
        
        outputs =  net(inputs)
        loss = criterion(outpus, labels)
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item()
        
        if i %2000 == 1999:
            print([%d, %5d] loss: %.3f' %
                  (epoch + 1, i + 1, running_loss / 2000))
            running_loss = 0.0

print('Finished Training')